// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLIBjaxF2HIHgIGJqlwJOK1F9hMmKjcQ',
    appId: '1:1016976884235:web:c4fc2afbcaf1784769fd0e',
    messagingSenderId: '1016976884235',
    projectId: 're-anime-app',
    authDomain: 're-anime-app.firebaseapp.com',
    storageBucket: 're-anime-app.firebasestorage.app',
    measurementId: 'G-1FRH1V3430',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwauVqEz2dZSOrKzETOd00nFs33NoG03k',
    appId: '1:1016976884235:android:bdb12dd04e1e690869fd0e',
    messagingSenderId: '1016976884235',
    projectId: 're-anime-app',
    storageBucket: 're-anime-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGEQQ8Njv2E6iARYIXiA6pcEcoeqBTKzI',
    appId: '1:1016976884235:ios:235aebbcbaf26c1669fd0e',
    messagingSenderId: '1016976884235',
    projectId: 're-anime-app',
    storageBucket: 're-anime-app.firebasestorage.app',
    iosBundleId: 'com.example.reAnimeApp',
  );
}
